name: Build and Test
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    main:
        name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
        with:
            node-version: 18
            npm-version: 9
            number-of-agents: 3
            parallel-commands: |
                npx nx-cloud record -- npx nx format:check
            parallel-commands-on-agents: |
                npx nx affected -t lint & npx nx affected -t test -c ci & npx nx affected -t build
    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
        with:
            number-of-agents: 3
            node-version: 18
            npm-version: 9
