name: Build and Test
# Needed for the main job to retrieve the appropriate SHAs when running on the main branch
permissions:
    actions: read
    contents: read
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Restore cache
              uses: actions/cache/restore@v3
              with:
                  key: npm-dependencies-${{ hashFiles('package-lock.json') }}
                  path: |
                      node_modules
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Cache npm dependencies
              uses: actions/cache/save@v3
              with:
                  key: npm-dependencies-${{ hashFiles('package-lock.json') }}
                  path: |
                      node_modules
            - name: Start up Nx Cloud agents
              run: npx nx-cloud start-ci-run --stop-agents-after "test"
            - name: Set Nx branch references
              uses: nrwl/nx-set-shas@v3
            - name: Track main branch
              run: git branch --track main origin/main
            - name: Check formatting
              run: npx nx-cloud record -- nx format:check
            - name: Check linting
              run: npx nx affected -t lint --no-agents
            - name: Create font-end client production environment file
              run: echo "${{ vars.CLIENT_ENV_VARIABLES_PROD }}" > projects/front-end/src/environments/environment.prod.ts
            - name: Create builds
              run: npx nx affected -t build --no-agents
              env:
                  JWT_SECRET: ${{ vars.JWT_SECRET }}
                  COOKIE_SECRET: ${{ vars.COOKIE_SECRET }}
            - name: Run tests
              run: npx nx affected -t test --no-agents
              env:
                  JWT_SECRET: ${{ vars.JWT_SECRET }}
                  COOKIE_SECRET: ${{ vars.COOKIE_SECRET }}
