name: Build and Test
# Needed for the main job to retrieve the appropriate SHAs when running on the main branch
permissions:
    actions: read
    contents: read
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    setup:
        name: Setup repo
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: prepare client environment variables
              run: |
                  echo "${{ vars.CLIENT_ENV_VARIABLES_PROD }}" > packages/client/src/environments/environment.prod.ts
    main:
        name: Nx Cloud - Main Job
        needs: setup
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
        with:
            main-branch-name: main
            node-version: 18
            npm-version: 9
            number-of-agents: 3
            init-commands: |
                npx nx-cloud start-ci-run --stop-agents-after "build" --agent-count 3
            parallel-commands: |
                npx nx-cloud record -- npx nx format:check
            parallel-commands-on-agents: |
                npx nx affected -t lint 
                npx nx affected -t test 
                npx nx affected -t build
    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
        with:
            number-of-agents: 3
            node-version: 18
            npm-version: 9
            environment-variables: |
                JWT_SECRET=${{ vars.JWT_SECRET }}
