name: Dnd-Mapp Docker images
on:
    push:
        branches: main
jobs:
    build-client-docker-image:
        uses: nonamer777/dnd-mapp/.github/workflows/client-docker-image.yaml
    build-server-docker-image:
        uses: nonamer777/dnd-mapp/.github/workflows/server-docker-image.yaml
