name: Create and publish a Docker image
on: push
env:
    REGISTRY: ghcr.io
    REPOSITORY: dnd-mapp
jobs:
    build-and-push-docker-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: packages/client/Dockerfile
                  push: true
                  tags: dnd-mapp/client:edge
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
